# ===============================================================
# === CORE (Core.ps1) — winws2 / zapret2 / Lua ===
# ===============================================================
#  Ядро: состояние $Global:ZapretState, загрузка/сохранение settings.yml,
#  конвертеры (Int, Bool), YAML-парсер, Write-Log.
#
#  ВАЖНО: Save-Settings теперь НЕ перезаписывает settings.yml целиком.
#  Он обновляет только значения конкретных ключей, сохраняя
#  комментарии, порядок, отступы и всё, что дописано руками.
# ===============================================================

$configPath = Join-Path $PSScriptRoot '..\config\settings.yml'
$configPath = [System.IO.Path]::GetFullPath($configPath)

$Global:ZapretState = @{
    # ─── Пути ───
    Winws2Path        = ""
    LuaLibPath        = ""
    LuaAntiDpiPath    = ""
    TxtPath           = ""
    BinPath           = ""

    # ─── Основное ───
    Tool              = "auto"
    WarmupSec         = 3
    TimeoutSec        = 4
    MaxDomains        = 0
    MinScore          = 1
    MinScorePercent   = 0
    TopN              = 20
    TargetScore       = 0
    PreTestCount      = 0
    PreTestPassScore  = 0
    PreTestUrls       = ""
    PreTestAllDomains = $false
    RandomCount       = 0
    BaselineCheckCount = 40
    AutoStopOnPerfect = $true
    KeepAllWorking    = $true

    # ─── Провайдер ───
    ProviderProfile   = ""

    # ─── Lua-методы ───
    LuaMethods        = @()

    # ─── Встроенные blob'ы ───
    LuaBlobs          = @()
    LuaBlobFiles      = @()
    LuaBlobFileMap    = @{}

    # ─── Fooling-параметры (LuaFool_*) ───
    LuaFool           = @{}

    # ─── Глобальные опции (Glob_*) ───
    Glob              = @{}

    # ─── DNS / DoH ───
    DnsServers        = @()
    DnsServerKeys     = @()
    DnsTestDomain     = "youtube.com"
    DohServers        = @()
    DohServerKeys     = @()
    DohTestDomain     = "youtube.com"

    # ─── Файлы ───
    ResultFile        = "resultats/resultat.txt"
    ProgressFile      = "config/progress.xml"
    Hostlist          = "list-general.txt"
    HostlistExclude   = "list-exclude.txt"

    # ─── Служебное ───
    ConfigFile        = $configPath
    Strategies        = @()
    Running           = $false
    LuaReady          = $false
}

function Test-Admin {
    $id = [Security.Principal.WindowsIdentity]::GetCurrent()
    $p  = New-Object Security.Principal.WindowsPrincipal($id)
    return $p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Get-Winws2Dir {
    if ($Global:ZapretState.Winws2Path -and (Test-Path $Global:ZapretState.Winws2Path)) {
        $item = Get-Item $Global:ZapretState.Winws2Path
        if ($item.PSIsContainer) { return $item.FullName }
        return $item.DirectoryName
    }
    return $null
}

function Get-ProcName { return 'winws2' }

# === YAML PARSER ===
function ConvertFrom-SimpleYaml {
    param([string]$Raw)

    $hash = @{}
    $lineNo = 0

    foreach ($line in ($Raw -split "`r?`n")) {
        $lineNo++
        $line = $line -replace '(^|\s)#.*$','$1'
        $trim = $line.Trim()
        if ($trim -eq "") { continue }
        if ($trim.StartsWith("#")) { continue }
        if ($trim -notmatch '^([^:]+):\s*(.*)$') { continue }

        $key   = $Matches[1].Trim()
        $value = $Matches[2].Trim()

        if ($value.Length -ge 2) {
            if (($value.StartsWith('"') -and $value.EndsWith('"')) -or
                ($value.StartsWith("'") -and $value.EndsWith("'"))) {
                $value = $value.Substring(1, $value.Length - 2)
            }
        }

        if ($hash.ContainsKey($key)) {
            Write-Host ("  [!] settings.yml: дубль ключа '{0}' (строка {1})" -f $key, $lineNo) -ForegroundColor Yellow
        }
        $hash[$key] = $value
    }
    return $hash
}

function ConvertTo-SimpleYaml {
    param($Hash)
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine("# Zapret Manager 2 (winws2) settings")
    [void]$sb.AppendLine("# Autogenerated $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
    [void]$sb.AppendLine("")
    foreach ($k in @($Hash.Keys)) {
        $v = $Hash[$k]; if ($null -eq $v) { $v = "" }
        [void]$sb.AppendLine("${k}: `"$v`"")
    }
    return $sb.ToString()
}

# ============================================================================
#  УМНОЕ ОБНОВЛЕНИЕ settings.yml (сохраняет комментарии и структуру)
# ============================================================================

# Обновить/добавить ОДИН ключ, сохранив остальные строки файла как есть.
function Set-YamlValue {
    param(
        [string]$File,
        [string]$Key,
        [string]$Value
    )

    if (-not (Test-Path $File)) {
        [System.IO.File]::WriteAllText($File, "", [Text.UTF8Encoding]::new($true))
    }

    $lines = New-Object System.Collections.Generic.List[string]
    $lines.AddRange([System.IO.File]::ReadAllLines($File, [Text.Encoding]::UTF8))

    $escaped = [regex]::Escape($Key)
    $found = $false

    for ($i = 0; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -match "^(\s*)$escaped(\s*):") {
            $prefix = $Matches[1]
            $lines[$i] = "$prefix$Key`: `"$Value`""
            $found = $true
            break
        }
    }

    if (-not $found) {
        # ключа не было — добавим в конец файла
        # (сначала пустая строка для разделения, если файл не пуст)
        if ($lines.Count -gt 0 -and -not [string]::IsNullOrWhiteSpace($lines[$lines.Count - 1])) {
            $lines.Add("")
        }
        $lines.Add("$Key`: `"$Value`"")
    }

    [System.IO.File]::WriteAllLines($File, $lines.ToArray(), [Text.UTF8Encoding]::new($true))
}

# Заменить ВСЕ ключи с указанным префиксом (например, "LuaBlobFile_",
# "Dns_", "Doh_"). Сохраняет позицию первого такого ключа в файле.
function Set-YamlSection {
    param(
        [string]$File,
        [string]$Prefix,
        [string[]]$NewLines = @()
    )

    if (-not (Test-Path $File)) { return }
    if ($NewLines -eq $null) { $NewLines = @() }

    $lines = New-Object System.Collections.Generic.List[string]
    $lines.AddRange([System.IO.File]::ReadAllLines($File, [Text.Encoding]::UTF8))

    $escaped = [regex]::Escape($Prefix)
    $pattern = "^${escaped}[A-Za-z0-9_]*\s*:"

    $firstIdx = -1
    for ($i = 0; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -match $pattern) {
            if ($firstIdx -lt 0) { $firstIdx = $i }
        }
    }

    $newList = New-Object System.Collections.Generic.List[string]
    foreach ($l in $lines) {
        if ($l -match $pattern) { continue }
        $newList.Add($l)
    }

    # свернём 3+ пустых строк подряд в одну
    $compact = New-Object System.Collections.Generic.List[string]
    $prevEmpty = $false
    foreach ($l in $newList) {
        $isEmpty = [string]::IsNullOrWhiteSpace($l)
        if ($isEmpty -and $prevEmpty) { continue }
        $compact.Add($l)
        $prevEmpty = $isEmpty
    }

    if ($NewLines.Count -gt 0) {
        if ($firstIdx -ge 0 -and $firstIdx -le $compact.Count) {
            $compact.InsertRange($firstIdx, [string[]]$NewLines)
        } else {
            if ($compact.Count -gt 0 -and -not [string]::IsNullOrWhiteSpace($compact[$compact.Count - 1])) {
                $compact.Add("")
            }
            foreach ($nl in $NewLines) { $compact.Add($nl) }
        }
    }

    [System.IO.File]::WriteAllLines($File, $compact.ToArray(), [Text.UTF8Encoding]::new($true))
}

# === CONVERTERS ===
function ConvertTo-Int {
    param($Value, [int]$Default = 0)
    if ($null -eq $Value) { return $Default }
    $n = 0
    if ([int]::TryParse("$Value", [ref]$n)) { return $n }
    return $Default
}

function ConvertTo-Bool {
    param($Value, [bool]$Default = $false)
    if ($null -eq $Value) { return $Default }
    $s = "$Value".Trim().ToLower()
    if ($s -in @('true','1','yes','on','да'))   { return $true }
    if ($s -in @('false','0','no','off','нет')) { return $false }
    return $Default
}

function Get-YamlValue {
    param($Data, [string]$Key)
    if ($null -eq $Data) { return $null }
    if ($Data -is [hashtable]) { return $Data[$Key] }
    $p = $Data.PSObject.Properties[$Key]
    if ($p) { return $p.Value }
    return $null
}

# ============================================================================
#  АВТО-СКАНИРОВАНИЕ .bin в папке BinPath
# ============================================================================
function Update-Winws2BlobFiles {
    $binDir = [string]$Global:ZapretState.BinPath
    if (-not $binDir -or -not (Test-Path -LiteralPath $binDir)) {
        return [pscustomobject]@{ Removed = 0; Added = 0; Total = 0; Skipped = $true }
    }

    $keepNames = New-Object System.Collections.Generic.List[string]
    $keepMap   = @{}
    $removed   = 0
    foreach ($name in $Global:ZapretState.LuaBlobFiles) {
        $fileName = $Global:ZapretState.LuaBlobFileMap[$name]
        if (-not $fileName) { continue }
        $fullPath = Join-Path $binDir $fileName
        if (Test-Path -LiteralPath $fullPath -PathType Leaf) {
            $keepNames.Add($name)
            $keepMap[$name] = $fileName
        } else {
            $removed++
        }
    }

    $existingFileNames = @($keepMap.Values)
    $added = 0
    foreach ($f in @(Get-ChildItem -LiteralPath $binDir -Filter '*.bin' -File -ErrorAction SilentlyContinue)) {
        if ($existingFileNames -contains $f.Name) { continue }

        $baseName = [IO.Path]::GetFileNameWithoutExtension($f.Name)
        $key = ($baseName -replace '[^A-Za-z0-9_]', '_')
        if ($key -match '^\d') { $key = "B$key" }

        $suffix = 1
        $originalKey = $key
        while ($keepMap.ContainsKey($key)) {
            $key = "$originalKey`_$suffix"
            $suffix++
        }

        $keepNames.Add($key)
        $keepMap[$key] = $f.Name
        $added++
    }

    $Global:ZapretState.LuaBlobFiles   = @($keepNames)
    $Global:ZapretState.LuaBlobFileMap = $keepMap

    return [pscustomobject]@{
        Removed = $removed
        Added   = $added
        Total   = $keepNames.Count
        Skipped = $false
    }
}

# ============================================================================
#  АВТО-СКАНИРОВАНИЕ .lua
# ============================================================================
function Get-AllLuaScripts {
    $libPath = [string]$Global:ZapretState.LuaLibPath
    if (-not $libPath) { return @() }
    $dir = Split-Path $libPath -Parent
    if (-not $dir -or -not (Test-Path -LiteralPath $dir)) { return @() }
    return @(Get-ChildItem -LiteralPath $dir -Filter '*.lua' -File -ErrorAction SilentlyContinue |
             Select-Object -ExpandProperty FullName)
}

# === Import-Settings ===
function Import-Settings {
    $file = $Global:ZapretState.ConfigFile

    Write-Host ""
    Write-Host "  ─── Import-Settings (winws2) ─────────────────" -ForegroundColor DarkMagenta
    Write-Host ("  ConfigFile: {0}" -f $file) -ForegroundColor Gray

    if (-not (Test-Path $file)) {
        Write-Host "  [!] Файл не найден, оставляю дефолты" -ForegroundColor Yellow
        return
    }

    try { $raw = [System.IO.File]::ReadAllText($file, [System.Text.Encoding]::UTF8) }
    catch { Write-Host ("  [!] Ошибка чтения: {0}" -f $_) -ForegroundColor Red; return }

    $data = ConvertFrom-SimpleYaml $raw
    $keyCount = 0
    if ($data -is [hashtable]) { $keyCount = $data.Keys.Count }
    Write-Host ("  Ключей загружено: {0}" -f $keyCount) -ForegroundColor Gray

    if ($keyCount -eq 0) {
        Write-Host "  [!] Парсер вернул 0 ключей" -ForegroundColor Yellow
        return
    }

    # ─── Читаем methods.yml (если есть) и мержим в $data ───
    $methodsFile = Join-Path (Split-Path $file -Parent) 'methods.yml'
    if (Test-Path $methodsFile) {
        try {
            $mRaw = [System.IO.File]::ReadAllText($methodsFile, [System.Text.Encoding]::UTF8)
            $mData = ConvertFrom-SimpleYaml $mRaw
            foreach ($k in $mData.Keys) {
                $data[$k] = $mData[$k]     # methods.yml имеет приоритет над settings.yml
            }
            Write-Host ("  methods.yml: {0} ключей (приоритет над settings.yml)" -f $mData.Keys.Count) -ForegroundColor DarkCyan
        } catch {
            Write-Host ("  [!] Ошибка чтения methods.yml: {0}" -f $_) -ForegroundColor Red
        }
    } else {
        Write-Host "  methods.yml не найден — читаю только settings.yml" -ForegroundColor DarkGray
    }

    # ─── Пути ───
    $v = Get-YamlValue $data 'Winws2Path';     if ($v) { $Global:ZapretState.Winws2Path     = [string]$v }
    $v = Get-YamlValue $data 'LuaLibPath';     if ($v) { $Global:ZapretState.LuaLibPath     = [string]$v }
    $v = Get-YamlValue $data 'LuaAntiDpiPath'; if ($v) { $Global:ZapretState.LuaAntiDpiPath = [string]$v }
    $v = Get-YamlValue $data 'TxtPath';        if ($v) { $Global:ZapretState.TxtPath        = [string]$v }
    $v = Get-YamlValue $data 'BinPath';        if ($v) { $Global:ZapretState.BinPath        = [string]$v }

    # ─── Основное ───
    $v = Get-YamlValue $data 'Tool';                if ($v) { $Global:ZapretState.Tool = [string]$v }
    $v = Get-YamlValue $data 'WarmupSec';           if ($null -ne $v) { $Global:ZapretState.WarmupSec = ConvertTo-Int $v 3 }
    $v = Get-YamlValue $data 'TimeoutSec';          if ($null -ne $v) { $Global:ZapretState.TimeoutSec = ConvertTo-Int $v 4 }
    $v = Get-YamlValue $data 'MaxDomains';          if ($null -ne $v) { $Global:ZapretState.MaxDomains = ConvertTo-Int $v 0 }
    $v = Get-YamlValue $data 'MinScore';            if ($null -ne $v) { $Global:ZapretState.MinScore = ConvertTo-Int $v 1 }
    $v = Get-YamlValue $data 'MinScorePercent';     if ($null -ne $v) { $Global:ZapretState.MinScorePercent = ConvertTo-Int $v 0 }
    $v = Get-YamlValue $data 'TopN';                if ($null -ne $v) { $Global:ZapretState.TopN = ConvertTo-Int $v 20 }
    $v = Get-YamlValue $data 'TargetScore';         if ($null -ne $v) { $Global:ZapretState.TargetScore = ConvertTo-Int $v 0 }
    $v = Get-YamlValue $data 'PreTestCount';        if ($null -ne $v) { $Global:ZapretState.PreTestCount = ConvertTo-Int $v 0 }
    $v = Get-YamlValue $data 'PreTestPassScore';    if ($null -ne $v) { $Global:ZapretState.PreTestPassScore = ConvertTo-Int $v 0 }
    $v = Get-YamlValue $data 'PreTestUrls';         if ($null -ne $v) { $Global:ZapretState.PreTestUrls = [string]$v }
    $v = Get-YamlValue $data 'PreTestAllDomains';   if ($null -ne $v) { $Global:ZapretState.PreTestAllDomains = ConvertTo-Bool $v $false }
    $v = Get-YamlValue $data 'RandomCount';         if ($null -ne $v) { $Global:ZapretState.RandomCount = ConvertTo-Int $v 0 }
    $v = Get-YamlValue $data 'BaselineCheckCount';  if ($null -ne $v) { $Global:ZapretState.BaselineCheckCount = ConvertTo-Int $v 40 }
    $v = Get-YamlValue $data 'AutoStopOnPerfect';   if ($null -ne $v) { $Global:ZapretState.AutoStopOnPerfect = ConvertTo-Bool $v $true }
    $v = Get-YamlValue $data 'KeepAllWorking';      if ($null -ne $v) { $Global:ZapretState.KeepAllWorking = ConvertTo-Bool $v $true }

    $v = Get-YamlValue $data 'ResultFile';     if ($v) { $Global:ZapretState.ResultFile = [string]$v }
    $v = Get-YamlValue $data 'ProgressFile';   if ($v) { $Global:ZapretState.ProgressFile = [string]$v }
    $v = Get-YamlValue $data 'Hostlist';       if ($v) { $Global:ZapretState.Hostlist = [string]$v }
    $v = Get-YamlValue $data 'HostlistExclude';if ($v) { $Global:ZapretState.HostlistExclude = [string]$v }

    # ─── Провайдер ───
    $v = Get-YamlValue $data 'ProviderProfile'; if ($v) { $Global:ZapretState.ProviderProfile = [string]$v }

    # ─── Lua-методы ───
    $Global:ZapretState.LuaMethods = @()
    foreach ($k in $data.Keys) {
        if ($k -match '^LuaMethod_(.+)$') {
            $val = [string]$data[$k]
            if ($val) { $Global:ZapretState.LuaMethods += $val }
        }
    }
    if ($Global:ZapretState.LuaMethods.Count -eq 0) {
        $Global:ZapretState.LuaMethods = @('fake','multisplit','multidisorder','fakeddisorder','hostfakesplit','syndata')
    }

    # ─── Встроенные blob'ы ───
    $Global:ZapretState.LuaBlobs = @()
    foreach ($k in $data.Keys) {
        if ($k -match '^LuaBlob_(?!File_)') {
            $val = [string]$data[$k]
            if ($val) { $Global:ZapretState.LuaBlobs += $val }
        }
    }

    # ─── Файловые blob'ы ───
    $Global:ZapretState.LuaBlobFiles   = @()
    $Global:ZapretState.LuaBlobFileMap = @{}
    foreach ($k in $data.Keys) {
        if ($k -match '^LuaBlobFile_([A-Za-z0-9_]+)$') {
            $name = $Matches[1]
            $val  = [string]$data[$k]
            if ($val) {
                $Global:ZapretState.LuaBlobFiles += $name
                $Global:ZapretState.LuaBlobFileMap[$name] = $val
            }
        }
    }

    # ─── АВТО-СКАН .bin ───
    $blobScan = Update-Winws2BlobFiles
    if (-not $blobScan.Skipped) {
        Write-Host ("  [auto] .bin: было в map={0}, удалено мёртвых={1}, добавлено новых={2}, итого={3}" -f `
            ($blobScan.Total - $blobScan.Added + $blobScan.Removed),
            $blobScan.Removed, $blobScan.Added, $blobScan.Total) -ForegroundColor DarkCyan
    } else {
        Write-Host "  [auto] BinPath не задан или не существует — авто-скан .bin пропущен" -ForegroundColor DarkYellow
    }

    # ─── Fooling-параметры ───
    $Global:ZapretState.LuaFool = @{}
    foreach ($k in $data.Keys) {
        if ($k -match '^LuaFool_([A-Za-z0-9_]+)$') {
            $name = $Matches[1]
            $val  = [string]$data[$k]
            if ($val) { $Global:ZapretState.LuaFool[$name] = $val }
        }
    }

    # ─── Глобальные опции ───
    $Global:ZapretState.Glob = @{}
    foreach ($k in $data.Keys) {
        if ($k -match '^Glob_([A-Za-z0-9_]+)$') {
            $name = $Matches[1]
            $val  = [string]$data[$k]
            if ($val -ne '') { $Global:ZapretState.Glob[$name] = $val }
        }
    }

    # ─── DNS ───
    $Global:ZapretState.DnsServers    = @()
    $Global:ZapretState.DnsServerKeys = @()
    foreach ($k in $data.Keys) {
        if ($k -eq 'DnsTestDomain') { continue }
        if ($k -match '^Dns_([A-Za-z0-9_]+)$') {
            $val = [string]$data[$k]
            if ($val -match '^\d{1,3}(\.\d{1,3}){3}$') {
                $Global:ZapretState.DnsServers    += $val
                $Global:ZapretState.DnsServerKeys += $k
            }
        }
    }
    $v = Get-YamlValue $data 'DnsTestDomain'; if ($v) { $Global:ZapretState.DnsTestDomain = [string]$v }

    # ─── DoH ───
    $Global:ZapretState.DohServers    = @()
    $Global:ZapretState.DohServerKeys = @()
    foreach ($k in $data.Keys) {
        if ($k -eq 'DohTestDomain') { continue }
        if ($k -match '^Doh_([A-Za-z0-9_]+)$') {
            $val = [string]$data[$k]
            if ($val -match '^https://') {
                $Global:ZapretState.DohServers    += $val
                $Global:ZapretState.DohServerKeys += $k
            }
        }
    }
    $v = Get-YamlValue $data 'DohTestDomain'; if ($v) { $Global:ZapretState.DohTestDomain = [string]$v }

    # ─── Проверка Lua ───
    $libFile  = Resolve-Winws2LuaPath -Path $Global:ZapretState.LuaLibPath     -TargetName 'zapret-lib.lua'
    $antiFile = Resolve-Winws2LuaPath -Path $Global:ZapretState.LuaAntiDpiPath -TargetName 'zapret-antidpi.lua'

    $libOk  = [bool]$libFile
    $antiOk = [bool]$antiFile
    $Global:ZapretState.LuaReady = ($libOk -and $antiOk)

    if ($libFile)  { $Global:ZapretState.LuaLibPath     = $libFile }
    if ($antiFile) { $Global:ZapretState.LuaAntiDpiPath = $antiFile }

    $allLua = @(Get-AllLuaScripts)
    $luaDir = if ($libFile) { Split-Path $libFile -Parent } else { $null }

    # ─── Отчёт ───
    Write-Host ("  LuaMethods={0}  Blobs={1}  BlobFiles={2}" -f `
        $Global:ZapretState.LuaMethods.Count,
        $Global:ZapretState.LuaBlobs.Count,
        $Global:ZapretState.LuaBlobFiles.Count) -ForegroundColor Gray
    Write-Host ("  Lua: lib={0}  antidpi={1}  ready={2}" -f `
        $(if ($libOk) {"OK"} else {"NO"}),
        $(if ($antiOk) {"OK"} else {"NO"}),
        $Global:ZapretState.LuaReady) -ForegroundColor $(if ($Global:ZapretState.LuaReady) {"Green"} else {"Red"})
    if ($luaDir) {
        $names = ($allLua | ForEach-Object { Split-Path $_ -Leaf }) -join ', '
        Write-Host ("  Lua-файлы в папке ({0}): {1}" -f $allLua.Count, $names) -ForegroundColor DarkCyan
    }
    Write-Host ("  .bin-файлы ({0}): {1}" -f `
        $Global:ZapretState.LuaBlobFiles.Count,
        ($Global:ZapretState.LuaBlobFileMap.Values -join ', ')) -ForegroundColor DarkCyan
    Write-Host ("  DNS={0}  DoH={1}" -f $Global:ZapretState.DnsServers.Count, $Global:ZapretState.DohServers.Count) -ForegroundColor Gray
    Write-Host ("  LuaFool={0}  Glob={1}" -f $Global:ZapretState.LuaFool.Count, $Global:ZapretState.Glob.Count) -ForegroundColor DarkCyan
    Write-Host ("  ProviderProfile={0}" -f $Global:ZapretState.ProviderProfile) -ForegroundColor DarkCyan
    Write-Host "  ────────────────────────────────────────────" -ForegroundColor DarkMagenta
    Write-Host ""
}

# === SAVE-SETTINGS ===
# ВАЖНО: НЕ перезаписывает settings.yml целиком!
# Обновляет только значения конкретных ключей, сохраняя комментарии,
# порядок строк и всё, что дописано руками.
function Save-Settings {
    $file = $Global:ZapretState.ConfigFile

    # убедимся, что файл существует
    if (-not (Test-Path $file)) {
        $dir = Split-Path $file -Parent
        if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
        [System.IO.File]::WriteAllText($file, "", [Text.UTF8Encoding]::new($true))
    }

    # ─── Пути ───
    Set-YamlValue -File $file -Key 'Winws2Path'      -Value $Global:ZapretState.Winws2Path
    Set-YamlValue -File $file -Key 'LuaLibPath'      -Value $Global:ZapretState.LuaLibPath
    Set-YamlValue -File $file -Key 'LuaAntiDpiPath'  -Value $Global:ZapretState.LuaAntiDpiPath
    Set-YamlValue -File $file -Key 'TxtPath'         -Value $Global:ZapretState.TxtPath
    Set-YamlValue -File $file -Key 'BinPath'         -Value $Global:ZapretState.BinPath

    # ─── Основное ───
    Set-YamlValue -File $file -Key 'Tool'              -Value $Global:ZapretState.Tool
    Set-YamlValue -File $file -Key 'WarmupSec'         -Value ([string]$Global:ZapretState.WarmupSec)
    Set-YamlValue -File $file -Key 'TimeoutSec'        -Value ([string]$Global:ZapretState.TimeoutSec)
    Set-YamlValue -File $file -Key 'MaxDomains'        -Value ([string]$Global:ZapretState.MaxDomains)
    Set-YamlValue -File $file -Key 'MinScore'          -Value ([string]$Global:ZapretState.MinScore)
    Set-YamlValue -File $file -Key 'MinScorePercent'   -Value ([string]$Global:ZapretState.MinScorePercent)
    Set-YamlValue -File $file -Key 'TopN'              -Value ([string]$Global:ZapretState.TopN)
    Set-YamlValue -File $file -Key 'TargetScore'       -Value ([string]$Global:ZapretState.TargetScore)
    Set-YamlValue -File $file -Key 'RandomCount'       -Value ([string]$Global:ZapretState.RandomCount)
    Set-YamlValue -File $file -Key 'BaselineCheckCount'-Value ([string]$Global:ZapretState.BaselineCheckCount)
    Set-YamlValue -File $file -Key 'AutoStopOnPerfect' -Value ([string]$Global:ZapretState.AutoStopOnPerfect)
    Set-YamlValue -File $file -Key 'KeepAllWorking'    -Value ([string]$Global:ZapretState.KeepAllWorking)

    # ─── Пре-тест ───
    Set-YamlValue -File $file -Key 'PreTestCount'      -Value ([string]$Global:ZapretState.PreTestCount)
    Set-YamlValue -File $file -Key 'PreTestPassScore'  -Value ([string]$Global:ZapretState.PreTestPassScore)
    Set-YamlValue -File $file -Key 'PreTestUrls'       -Value $Global:ZapretState.PreTestUrls
    Set-YamlValue -File $file -Key 'PreTestAllDomains' -Value ([string]$Global:ZapretState.PreTestAllDomains)

    # ─── Файлы / провайдер ───
    Set-YamlValue -File $file -Key 'ResultFile'        -Value $Global:ZapretState.ResultFile
    Set-YamlValue -File $file -Key 'ProgressFile'      -Value $Global:ZapretState.ProgressFile
    Set-YamlValue -File $file -Key 'Hostlist'          -Value $Global:ZapretState.Hostlist
    Set-YamlValue -File $file -Key 'HostlistExclude'   -Value $Global:ZapretState.HostlistExclude
    Set-YamlValue -File $file -Key 'ProviderProfile'   -Value $Global:ZapretState.ProviderProfile

    # ─── Lua-методы ───
    $methodLines = @()
    foreach ($m in $Global:ZapretState.LuaMethods) {
        $methodLines += ("LuaMethod_{0}: `"{1}`"" -f ($m -replace '[^A-Za-z0-9_]','_'), $m)
    }
    Set-YamlSection -File $file -Prefix 'LuaMethod_' -NewLines $methodLines

    # ─── Встроенные blob'ы ───
    $blobLines = @()
    foreach ($b in $Global:ZapretState.LuaBlobs) {
        $blobLines += ("LuaBlob_{0}: `"{1}`"" -f ($b -replace '[^A-Za-z0-9_]','_'), $b)
    }
    Set-YamlSection -File $file -Prefix 'LuaBlob_' -NewLines $blobLines

    # ─── Файловые blob'ы ───
    $bfLines = @()
    foreach ($name in $Global:ZapretState.LuaBlobFiles) {
        $fn = $Global:ZapretState.LuaBlobFileMap[$name]
        if (-not $fn) { continue }
        $bfLines += ("LuaBlobFile_{0}: `"{1}`"" -f $name, $fn)
    }
    Set-YamlSection -File $file -Prefix 'LuaBlobFile_' -NewLines $bfLines

    # ─── Fooling ───
    $foolLines = @()
    foreach ($k in $Global:ZapretState.LuaFool.Keys) {
        $foolLines += ("LuaFool_{0}: `"{1}`"" -f $k, $Global:ZapretState.LuaFool[$k])
    }
    Set-YamlSection -File $file -Prefix 'LuaFool_' -NewLines $foolLines

    # ─── Glob ───
    $globLines = @()
    foreach ($k in $Global:ZapretState.Glob.Keys) {
        $globLines += ("Glob_{0}: `"{1}`"" -f $k, $Global:ZapretState.Glob[$k])
    }
    Set-YamlSection -File $file -Prefix 'Glob_' -NewLines $globLines

    # ─── DNS ───
    Set-YamlValue -File $file -Key 'DnsTestDomain' -Value $Global:ZapretState.DnsTestDomain
    $dnsLines = @()
    for ($j = 0; $j -lt $Global:ZapretState.DnsServers.Count; $j++) {
        $key = if ($j -lt $Global:ZapretState.DnsServerKeys.Count -and $Global:ZapretState.DnsServerKeys[$j]) { $Global:ZapretState.DnsServerKeys[$j] } else { "Dns_Server$($j+1)" }
        $dnsLines += ("{0}: `"{1}`"" -f $key, $Global:ZapretState.DnsServers[$j])
    }
    Set-YamlSection -File $file -Prefix 'Dns_' -NewLines $dnsLines

    # ─── DoH ───
    Set-YamlValue -File $file -Key 'DohTestDomain' -Value $Global:ZapretState.DohTestDomain
    $dohLines = @()
    for ($j = 0; $j -lt $Global:ZapretState.DohServers.Count; $j++) {
        $key = if ($j -lt $Global:ZapretState.DohServerKeys.Count -and $Global:ZapretState.DohServerKeys[$j]) { $Global:ZapretState.DohServerKeys[$j] } else { "Doh_Server$($j+1)" }
        $dohLines += ("{0}: `"{1}`"" -f $key, $Global:ZapretState.DohServers[$j])
    }
    Set-YamlSection -File $file -Prefix 'Doh_' -NewLines $dohLines

    Write-Log "settings.yml updated (in-place)"
}

# === WRITE-LOG ===
function Write-Log($msg, $level = "INFO") {
    $time = Get-Date -Format "HH:mm:ss"
    $color = switch ($level) { "ERR" { "Red" } "WARN" { "Yellow" } default { "Green" } }
    Write-Host "[$time][$level] $msg" -ForegroundColor $color
}