# ===============================================================
# === CORE (Core.ps1) — winws2 / zapret2 / Lua ===
# ===============================================================
#  Ядро: состояние $Global:ZapretState, загрузка/сохранение settings.yml,
#  конвертеры (Int, Bool), YAML-парсер, Write-Log.
# ===============================================================

$configPath = Join-Path $PSScriptRoot '..\config\settings.yml'
$configPath = [System.IO.Path]::GetFullPath($configPath)

$Global:ZapretState = @{
    # ─── Пути ───
    Winws2Path        = ""
    LuaLibPath        = ""
    LuaAntiDpiPath    = ""
    TxtPath           = ""
    BinPath           = ""

    # ─── Основное ───
    Tool              = "auto"
    WarmupSec         = 3
    TimeoutSec        = 4
    MaxDomains        = 0
    MinScore          = 1
    MinScorePercent   = 0
    TopN              = 20
    TargetScore       = 0
    PreTestCount      = 0
    PreTestPassScore  = 0
    PreTestUrls       = ""
    PreTestAllDomains = $false
    RandomCount       = 0
    BaselineCheckCount = 40
    AutoStopOnPerfect = $true
    KeepAllWorking    = $true

    # ─── Lua-методы ───
    LuaMethods        = @()

    # ─── Встроенные blob'ы ───
    LuaBlobs          = @()
    LuaBlobFiles      = @()
    LuaBlobFileMap    = @{}

    # ─── DNS / DoH ───
    DnsServers        = @()
    DnsServerKeys     = @()
    DnsTestDomain     = "youtube.com"
    DohServers        = @()
    DohServerKeys     = @()
    DohTestDomain     = "youtube.com"

    # ─── Файлы ───
    ResultFile        = "resultats/resultat.txt"
    ProgressFile      = "config/progress.xml"
    Hostlist          = "list-general.txt"
    HostlistExclude   = "list-exclude.txt"

    # ─── Служебное ───
    ConfigFile        = $configPath
    Strategies        = @()
    Running           = $false
    LuaReady          = $false
}

function Test-Admin {
    $id = [Security.Principal.WindowsIdentity]::GetCurrent()
    $p  = New-Object Security.Principal.WindowsPrincipal($id)
    return $p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Get-Winws2Dir {
    if ($Global:ZapretState.Winws2Path -and (Test-Path $Global:ZapretState.Winws2Path)) {
        $item = Get-Item $Global:ZapretState.Winws2Path
        if ($item.PSIsContainer) { return $item.FullName }
        return $item.DirectoryName
    }
    return $null
}

function Get-ProcName { return 'winws2' }

# === YAML PARSER ===
# Улучшенный парсер: корректно обрабатывает inline-комментарии только
# если перед # есть пробел, и предупреждает о дублях ключей.
function ConvertFrom-SimpleYaml {
    param([string]$Raw)

    $hash = @{}
    $lineNo = 0

    foreach ($line in ($Raw -split "`r?`n")) {
        $lineNo++
        # Убираем inline-комментарии: # только если перед ним пробел/начало строки
        $line = $line -replace '(^|\s)#.*$','$1'
        $trim = $line.Trim()
        if ($trim -eq "") { continue }
        if ($trim.StartsWith("#")) { continue }
        if ($trim -notmatch '^([^:]+):\s*(.*)$') { continue }

        $key   = $Matches[1].Trim()
        $value = $Matches[2].Trim()

        # Убираем кавычки
        if ($value.Length -ge 2) {
            if (($value.StartsWith('"') -and $value.EndsWith('"')) -or
                ($value.StartsWith("'") -and $value.EndsWith("'"))) {
                $value = $value.Substring(1, $value.Length - 2)
            }
        }

        if ($hash.ContainsKey($key)) {
            Write-Host ("  [!] settings.yml: дубль ключа '{0}' (строка {1})" -f $key, $lineNo) -ForegroundColor Yellow
        }
        $hash[$key] = $value
    }
    return $hash
}

function ConvertTo-SimpleYaml {
    param($Hash)
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine("# Zapret Manager 2 (winws2) settings")
    [void]$sb.AppendLine("# Autogenerated $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
    [void]$sb.AppendLine("")
    foreach ($k in @($Hash.Keys)) {
        $v = $Hash[$k]; if ($null -eq $v) { $v = "" }
        [void]$sb.AppendLine("${k}: `"$v`"")
    }
    return $sb.ToString()
}

# === CONVERTERS ===
function ConvertTo-Int {
    param($Value, [int]$Default = 0)
    if ($null -eq $Value) { return $Default }
    $n = 0
    if ([int]::TryParse("$Value", [ref]$n)) { return $n }
    return $Default
}

function ConvertTo-Bool {
    param($Value, [bool]$Default = $false)
    if ($null -eq $Value) { return $Default }
    $s = "$Value".Trim().ToLower()
    if ($s -in @('true','1','yes','on','да'))   { return $true }
    if ($s -in @('false','0','no','off','нет')) { return $false }
    return $Default
}

function Get-YamlValue {
    param($Data, [string]$Key)
    if ($null -eq $Data) { return $null }
    if ($Data -is [hashtable]) { return $Data[$Key] }
    $p = $Data.PSObject.Properties[$Key]
    if ($p) { return $p.Value }
    return $null
}

# === Import-Settings ===
function Import-Settings {
    $file = $Global:ZapretState.ConfigFile

    Write-Host ""
    Write-Host "  ─── Import-Settings (winws2) ─────────────────" -ForegroundColor DarkMagenta
    Write-Host ("  ConfigFile: {0}" -f $file) -ForegroundColor Gray

    if (-not (Test-Path $file)) {
        Write-Host "  [!] Файл не найден, оставляю дефолты" -ForegroundColor Yellow
        return
    }

    try { $raw = [System.IO.File]::ReadAllText($file, [System.Text.Encoding]::UTF8) }
    catch { Write-Host ("  [!] Ошибка чтения: {0}" -f $_) -ForegroundColor Red; return }

    $data = ConvertFrom-SimpleYaml $raw
    $keyCount = 0
    if ($data -is [hashtable]) { $keyCount = $data.Keys.Count }
    Write-Host ("  Ключей загружено: {0}" -f $keyCount) -ForegroundColor Gray

    if ($keyCount -eq 0) {
        Write-Host "  [!] Парсер вернул 0 ключей" -ForegroundColor Yellow
        return
    }

    # ─── Пути ───
    $v = Get-YamlValue $data 'Winws2Path';     if ($v) { $Global:ZapretState.Winws2Path     = [string]$v }
    $v = Get-YamlValue $data 'LuaLibPath';     if ($v) { $Global:ZapretState.LuaLibPath     = [string]$v }
    $v = Get-YamlValue $data 'LuaAntiDpiPath'; if ($v) { $Global:ZapretState.LuaAntiDpiPath = [string]$v }
    $v = Get-YamlValue $data 'TxtPath';        if ($v) { $Global:ZapretState.TxtPath        = [string]$v }
    $v = Get-YamlValue $data 'BinPath';        if ($v) { $Global:ZapretState.BinPath        = [string]$v }

    # ─── Основное ───
    $v = Get-YamlValue $data 'Tool';                if ($v) { $Global:ZapretState.Tool = [string]$v }
    $v = Get-YamlValue $data 'WarmupSec';           if ($null -ne $v) { $Global:ZapretState.WarmupSec = ConvertTo-Int $v 3 }
    $v = Get-YamlValue $data 'TimeoutSec';          if ($null -ne $v) { $Global:ZapretState.TimeoutSec = ConvertTo-Int $v 4 }
    $v = Get-YamlValue $data 'MaxDomains';          if ($null -ne $v) { $Global:ZapretState.MaxDomains = ConvertTo-Int $v 0 }
    $v = Get-YamlValue $data 'MinScore';            if ($null -ne $v) { $Global:ZapretState.MinScore = ConvertTo-Int $v 1 }
    $v = Get-YamlValue $data 'MinScorePercent';     if ($null -ne $v) { $Global:ZapretState.MinScorePercent = ConvertTo-Int $v 0 }
    $v = Get-YamlValue $data 'TopN';                if ($null -ne $v) { $Global:ZapretState.TopN = ConvertTo-Int $v 20 }
    $v = Get-YamlValue $data 'TargetScore';         if ($null -ne $v) { $Global:ZapretState.TargetScore = ConvertTo-Int $v 0 }
    $v = Get-YamlValue $data 'PreTestCount';        if ($null -ne $v) { $Global:ZapretState.PreTestCount = ConvertTo-Int $v 0 }
    $v = Get-YamlValue $data 'PreTestPassScore';    if ($null -ne $v) { $Global:ZapretState.PreTestPassScore = ConvertTo-Int $v 0 }
    $v = Get-YamlValue $data 'PreTestUrls';         if ($null -ne $v) { $Global:ZapretState.PreTestUrls = [string]$v }
    $v = Get-YamlValue $data 'PreTestAllDomains';   if ($null -ne $v) { $Global:ZapretState.PreTestAllDomains = ConvertTo-Bool $v $false }
    $v = Get-YamlValue $data 'RandomCount';         if ($null -ne $v) { $Global:ZapretState.RandomCount = ConvertTo-Int $v 0 }
    $v = Get-YamlValue $data 'BaselineCheckCount';  if ($null -ne $v) { $Global:ZapretState.BaselineCheckCount = ConvertTo-Int $v 40 }
    $v = Get-YamlValue $data 'AutoStopOnPerfect';   if ($null -ne $v) { $Global:ZapretState.AutoStopOnPerfect = ConvertTo-Bool $v $true }
    $v = Get-YamlValue $data 'KeepAllWorking';      if ($null -ne $v) { $Global:ZapretState.KeepAllWorking = ConvertTo-Bool $v $true }

    $v = Get-YamlValue $data 'ResultFile';     if ($v) { $Global:ZapretState.ResultFile = [string]$v }
    $v = Get-YamlValue $data 'ProgressFile';   if ($v) { $Global:ZapretState.ProgressFile = [string]$v }
    $v = Get-YamlValue $data 'Hostlist';       if ($v) { $Global:ZapretState.Hostlist = [string]$v }
    $v = Get-YamlValue $data 'HostlistExclude';if ($v) { $Global:ZapretState.HostlistExclude = [string]$v }

    # ─── Lua-методы ───
    $Global:ZapretState.LuaMethods = @()
    foreach ($k in $data.Keys) {
        if ($k -match '^LuaMethod_(.+)$') {
            $val = [string]$data[$k]
            if ($val) { $Global:ZapretState.LuaMethods += $val }
        }
    }
    if ($Global:ZapretState.LuaMethods.Count -eq 0) {
        $Global:ZapretState.LuaMethods = @('fake','multisplit','multidisorder','fakeddisorder','hostfakesplit','syndata')
    }

    # ─── Встроенные blob'ы ───
    $Global:ZapretState.LuaBlobs = @()
    foreach ($k in $data.Keys) {
        if ($k -match '^LuaBlob_(?!File_)') {
            $val = [string]$data[$k]
            if ($val) { $Global:ZapretState.LuaBlobs += $val }
        }
    }

    # ─── Файловые blob'ы ───
    $Global:ZapretState.LuaBlobFiles   = @()
    $Global:ZapretState.LuaBlobFileMap = @{}
    foreach ($k in $data.Keys) {
        if ($k -match '^LuaBlobFile_([A-Za-z0-9_]+)$') {
            $name = $Matches[1]
            $val  = [string]$data[$k]
            if ($val) {
                $Global:ZapretState.LuaBlobFiles += $name
                $Global:ZapretState.LuaBlobFileMap[$name] = $val
            }
        }
    }

    # ─── DNS ───
    $Global:ZapretState.DnsServers    = @()
    $Global:ZapretState.DnsServerKeys = @()
    foreach ($k in $data.Keys) {
        if ($k -eq 'DnsTestDomain') { continue }
        if ($k -match '^Dns_([A-Za-z0-9_]+)$') {
            $val = [string]$data[$k]
            if ($val -match '^\d{1,3}(\.\d{1,3}){3}$') {
                $Global:ZapretState.DnsServers    += $val
                $Global:ZapretState.DnsServerKeys += $k
            }
        }
    }
    $v = Get-YamlValue $data 'DnsTestDomain'; if ($v) { $Global:ZapretState.DnsTestDomain = [string]$v }

    # ─── DoH ───
    $Global:ZapretState.DohServers    = @()
    $Global:ZapretState.DohServerKeys = @()
    foreach ($k in $data.Keys) {
        if ($k -eq 'DohTestDomain') { continue }
        if ($k -match '^Doh_([A-Za-z0-9_]+)$') {
            $val = [string]$data[$k]
            if ($val -match '^https://') {
                $Global:ZapretState.DohServers    += $val
                $Global:ZapretState.DohServerKeys += $k
            }
        }
    }
    $v = Get-YamlValue $data 'DohTestDomain'; if ($v) { $Global:ZapretState.DohTestDomain = [string]$v }

    # ─── Проверка Lua (с резолвом папки → файла) ───
    $libFile  = Resolve-Winws2LuaPath -Path $Global:ZapretState.LuaLibPath     -TargetName 'zapret-lib.lua'
    $antiFile = Resolve-Winws2LuaPath -Path $Global:ZapretState.LuaAntiDpiPath -TargetName 'zapret-antidpi.lua'

    $libOk  = [bool]$libFile
    $antiOk = [bool]$antiFile
    $Global:ZapretState.LuaReady = ($libOk -and $antiOk)

    # Если путь был папкой — подменим на реальный файл, чтобы в отчёте было видно
    if ($libFile)  { $Global:ZapretState.LuaLibPath     = $libFile }
    if ($antiFile) { $Global:ZapretState.LuaAntiDpiPath = $antiFile }

    # ─── Отчёт ───
    Write-Host ("  LuaMethods={0}  Blobs={1}  BlobFiles={2}" -f `
        $Global:ZapretState.LuaMethods.Count,
        $Global:ZapretState.LuaBlobs.Count,
        $Global:ZapretState.LuaBlobFiles.Count) -ForegroundColor Gray
    Write-Host ("  Lua: lib={0}  antidpi={1}  ready={2}" -f `
        $(if ($libOk) {"OK"} else {"NO"}),
        $(if ($antiOk) {"OK"} else {"NO"}),
        $Global:ZapretState.LuaReady) -ForegroundColor $(if ($Global:ZapretState.LuaReady) {"Green"} else {"Red"})
    Write-Host ("  DNS={0}  DoH={1}" -f $Global:ZapretState.DnsServers.Count, $Global:ZapretState.DohServers.Count) -ForegroundColor Gray
    Write-Host "  ────────────────────────────────────────────" -ForegroundColor DarkMagenta
    Write-Host ""
}

# === SAVE-SETTINGS ===
function Save-Settings {
    $file = $Global:ZapretState.ConfigFile
    $dir  = Split-Path $file -Parent
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }

    $hash = [ordered]@{
        Winws2Path         = [string]$Global:ZapretState.Winws2Path
        LuaLibPath         = [string]$Global:ZapretState.LuaLibPath
        LuaAntiDpiPath     = [string]$Global:ZapretState.LuaAntiDpiPath
        TxtPath            = [string]$Global:ZapretState.TxtPath
        BinPath            = [string]$Global:ZapretState.BinPath
        Tool               = [string]$Global:ZapretState.Tool
        WarmupSec          = [string]$Global:ZapretState.WarmupSec
        TimeoutSec         = [string]$Global:ZapretState.TimeoutSec
        MaxDomains         = [string]$Global:ZapretState.MaxDomains
        MinScore           = [string]$Global:ZapretState.MinScore
        MinScorePercent    = [string]$Global:ZapretState.MinScorePercent
        TopN               = [string]$Global:ZapretState.TopN
        TargetScore        = [string]$Global:ZapretState.TargetScore
        PreTestCount       = [string]$Global:ZapretState.PreTestCount
        PreTestPassScore   = [string]$Global:ZapretState.PreTestPassScore
        PreTestUrls        = [string]$Global:ZapretState.PreTestUrls
        PreTestAllDomains  = [string]$Global:ZapretState.PreTestAllDomains
        RandomCount        = [string]$Global:ZapretState.RandomCount
        BaselineCheckCount = [string]$Global:ZapretState.BaselineCheckCount
        AutoStopOnPerfect  = [string]$Global:ZapretState.AutoStopOnPerfect
        KeepAllWorking     = [string]$Global:ZapretState.KeepAllWorking
        ResultFile         = [string]$Global:ZapretState.ResultFile
        ProgressFile       = [string]$Global:ZapretState.ProgressFile
        Hostlist           = [string]$Global:ZapretState.Hostlist
        HostlistExclude    = [string]$Global:ZapretState.HostlistExclude
    }

    Set-Content -Path $file -Value (ConvertTo-SimpleYaml $hash) -Encoding UTF8

    # Lua-методы и blob'ы
    $extra = "`r`n# === LUA METHODS / BLOBS ===`r`n"
    foreach ($m in $Global:ZapretState.LuaMethods) {
        $extra += ("LuaMethod_{0}: `"{1}`"`r`n" -f ($m -replace '[^A-Za-z0-9_]','_'), $m)
    }
    foreach ($b in $Global:ZapretState.LuaBlobs) {
        $extra += ("LuaBlob_{0}: `"{1}`"`r`n" -f ($b -replace '[^A-Za-z0-9_]','_'), $b)
    }
    foreach ($name in $Global:ZapretState.LuaBlobFiles) {
        $fn = $Global:ZapretState.LuaBlobFileMap[$name]
        $extra += ("LuaBlobFile_{0}: `"{1}`"`r`n" -f $name, $fn)
    }
    Add-Content -Path $file -Value $extra -Encoding UTF8

    # DNS
    $dnsBlock  = "`r`n# === DNS SERVERS (UDP) ===`r`n"
    $dnsBlock += ("DnsTestDomain: `"$($Global:ZapretState.DnsTestDomain)`"`r`n`r`n")
    for ($j = 0; $j -lt $Global:ZapretState.DnsServers.Count; $j++) {
        $key = if ($j -lt $Global:ZapretState.DnsServerKeys.Count -and $Global:ZapretState.DnsServerKeys[$j]) { $Global:ZapretState.DnsServerKeys[$j] } else { "Dns_Server$($j+1)" }
        $dnsBlock += ("{0}: `"{1}`"`r`n" -f $key, $Global:ZapretState.DnsServers[$j])
    }
    Add-Content -Path $file -Value $dnsBlock -Encoding UTF8

    # DoH
    $dohBlock  = "`r`n# === DNS-over-HTTPS (DoH) ===`r`n"
    $dohBlock += ("DohTestDomain: `"$($Global:ZapretState.DohTestDomain)`"`r`n`r`n")
    for ($j = 0; $j -lt $Global:ZapretState.DohServers.Count; $j++) {
        $key = if ($j -lt $Global:ZapretState.DohServerKeys.Count -and $Global:ZapretState.DohServerKeys[$j]) { $Global:ZapretState.DohServerKeys[$j] } else { "Doh_Server$($j+1)" }
        $dohBlock += ("{0}: `"{1}`"`r`n" -f $key, $Global:ZapretState.DohServers[$j])
    }
    Add-Content -Path $file -Value $dohBlock -Encoding UTF8

    Write-Log "settings.yml saved (winws2)"
}

# === WRITE-LOG ===
function Write-Log($msg, $level = "INFO") {
    $time = Get-Date -Format "HH:mm:ss"
    $color = switch ($level) { "ERR" { "Red" } "WARN" { "Yellow" } default { "Green" } }
    Write-Host "[$time][$level] $msg" -ForegroundColor $color
}