# ===============================================================
# === CORE (Core.ps1) ===
# ===============================================================
#  Ядро: состояние $Global:ZapretState, загрузка/сохранение settings.yml,
#  конвертеры (Int, Bool), YAML-парсер, Write-Log.
#
#  Только zapret1 (winws.exe).
# ===============================================================

# === CONFIG PATH ===
$configPath = Join-Path $PSScriptRoot '..\config\settings.yml'
$configPath = [System.IO.Path]::GetFullPath($configPath)

# === ZAPRESTATE INIT ===
$Global:ZapretState = @{
    # ─── Пути ───
    WinwsPath         = ""         # winws.exe
    TxtPath           = ""         # папка с .txt (hostlist)
    BinPath           = ""         # папка с .bin (fake payloads)

    # ─── Основное ───
    Tool              = "auto"
    WarmupSec         = 2
    TimeoutSec        = 4
    MaxDomains        = 0
    MinScore          = 1
    MinScorePercent   = 50
    TopN              = 20
    TargetScore       = 35
    PreTestCount      = 12
    PreTestPassScore  = 8
    PreTestUrls       = ""
    PreTestAllDomains = $false
    RandomCount       = 200
    BaselineCheckCount = 40
    AutoStopOnPerfect = $true
    KeepAllWorking    = $true
    TestDepth         = 2
    BinDepth          = 1

    # ─── Методы / позиции / фолы ───
    Methods           = @()
    SplitPositions    = @()
    Foolings          = @()
    Autottls          = @()

    # ─── Именованные Fake TLS ───
    FakeTLS_Google    = ""
    FakeTLS_Google2   = ""
    FakeTLS_MaxRu     = ""
    FakeTLS_4PDA      = ""
    FakeTLS_Sferum    = ""
    FakeTLS_5ka       = ""

    # ─── Именованные Fake QUIC ───
    FakeQUIC_Google   = ""
    FakeQUIC_Discord  = ""
    FakeQUIC_4PDA     = ""
    FakeQUIC_Rutube   = ""
    FakeQUIC_Steam    = ""
    FakeQUIC_Tencent  = ""
    FakeQUIC_5ka      = ""

    # ─── Именованные Fake UDP ───
    FakeUDP_STUN      = ""
    FakeUDP_STUN2     = ""
    FakeUDP_Game      = ""
    FakeUDP_Discord   = ""

    # ─── Общие пулы ───
    FakeTLSPool       = @()
    FakeQUICPool      = @()
    FakeUDPPool       = @()

    ForceBin          = $false
    UseFakeTLS        = $true
    UseFakeQUIC       = $false
    UseFakeHTTP       = $false

    DnsServers        = @("8.8.8.8","1.1.1.1","8.8.4.4","1.0.0.1")
    DnsServerKeys     = @("Dns_Google1","Dns_Cloudflare1","Dns_Google2","Dns_Cloudflare2")
    DnsTestDomain     = "youtube.com"

    DohServers        = @(
        "https://dns.google/dns-query",
        "https://cloudflare-dns.com/dns-query",
        "https://dns.adguard-dns.com/dns-query",
        "https://dns.quad9.net/dns-query"
    )
    DohServerKeys     = @("Doh_Google","Doh_Cloudflare","Doh_AdGuard","Doh_Quad9")
    DohTestDomain     = "youtube.com"

    ResultFile        = "resultats/resultat.txt"
    ProgressFile      = "config/progress.xml"

    Hostlist          = "list-general.txt"
    HostlistExclude   = "list-exclude.txt"

    ConfigFile        = $configPath
    Strategies        = @()
    Running           = $false
}

# === TEST-ADMIN ===
function Test-Admin {
    $id = [Security.Principal.WindowsIdentity]::GetCurrent()
    $p  = New-Object Security.Principal.WindowsPrincipal($id)
    return $p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

# === GET-WINWSDIR ===
function Get-WinwsDir {
    if ($Global:ZapretState.WinwsPath -and (Test-Path $Global:ZapretState.WinwsPath)) {
        $item = Get-Item $Global:ZapretState.WinwsPath
        if ($item.PSIsContainer) { return $item.FullName }
        return $item.DirectoryName
    }
    return $null
}

# === GET-PROCNAME ===
function Get-ProcName {
    return 'winws'
}

# === YAML PARSER ===
function ConvertFrom-SimpleYaml {
    param([string]$Raw)
    $hash = @{}
    foreach ($line in ($Raw -split "`r?`n")) {
        $line = $line -replace '\s+#.*$',''
        $trim = $line.Trim()
        if ($trim -eq "") { continue }
        if ($trim.StartsWith("#")) { continue }
        if ($trim -notmatch '^([^:]+):\s*(.*)$') { continue }

        $key   = $Matches[1].Trim()
        $value = $Matches[2].Trim()

        if ($value.Length -ge 2) {
            if (($value.StartsWith('"') -and $value.EndsWith('"')) -or
                ($value.StartsWith("'") -and $value.EndsWith("'"))) {
                $value = $value.Substring(1, $value.Length - 2)
            }
        }
        $hash[$key] = $value
    }
    return $hash
}

function ConvertTo-SimpleYaml {
    param($Hash)
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine("# Zapret Manager settings")
    [void]$sb.AppendLine("# Autogenerated $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
    [void]$sb.AppendLine("")
    $keys = @($Hash.Keys | Sort-Object)
    foreach ($k in $keys) {
        $v = $Hash[$k]
        if ($null -eq $v) { $v = "" }
        [void]$sb.AppendLine("${k}: `"$v`"")
    }
    return $sb.ToString()
}

# === CONVERTERS ===
function ConvertTo-Int {
    param($Value, [int]$Default = 0)
    if ($null -eq $Value) { return $Default }
    $n = 0
    if ([int]::TryParse("$Value", [ref]$n)) { return $n }
    return $Default
}

function ConvertTo-Bool {
    param($Value, [bool]$Default = $false)
    if ($null -eq $Value) { return $Default }
    $s = "$Value".Trim().ToLower()
    if ($s -in @('true','1','yes','on','да'))   { return $true }
    if ($s -in @('false','0','no','off','нет')) { return $false }
    return $Default
}

function Get-YamlValue {
    param($Data, [string]$Key)
    if ($null -eq $Data) { return $null }
    if ($Data -is [hashtable]) { return $Data[$Key] }
    $p = $Data.PSObject.Properties[$Key]
    if ($p) { return $p.Value }
    return $null
}

# === LOAD-SETTINGS ===
function Load-Settings {
    $file = $Global:ZapretState.ConfigFile

    Write-Host ""
    Write-Host "  ─── LOAD-SETTINGS ──────────────────────────" -ForegroundColor DarkCyan
    Write-Host ("  ConfigFile: {0}" -f $file) -ForegroundColor Gray

    if (-not (Test-Path $file)) {
        Write-Host "  [!] Файл не найден, оставляю дефолты" -ForegroundColor Yellow
        return
    }

    try {
        $raw = [System.IO.File]::ReadAllText($file, [System.Text.Encoding]::UTF8)
    } catch {
        Write-Host ("  [!] Ошибка чтения: {0}" -f $_) -ForegroundColor Red
        return
    }
    Write-Host ("  Прочитано байт: {0}" -f $raw.Length) -ForegroundColor Gray

    $data = ConvertFrom-SimpleYaml $raw
    $keyCount = 0
    if ($data -is [hashtable]) { $keyCount = $data.Keys.Count }
    Write-Host ("  Ключей загружено: {0}" -f $keyCount) -ForegroundColor Gray

    if ($keyCount -eq 0) {
        Write-Host "  [!] Парсер вернул 0 ключей" -ForegroundColor Yellow
        return
    }

    # ─── Пути ───
    $v = Get-YamlValue $data 'WinwsPath'
    if ($v) { $Global:ZapretState.WinwsPath = [string]$v }
    $v = Get-YamlValue $data 'TxtPath'
    if ($v) { $Global:ZapretState.TxtPath = [string]$v }
    $v = Get-YamlValue $data 'BinPath'
    if ($v) { $Global:ZapretState.BinPath = [string]$v }

    # ─── Основное ───
    $v = Get-YamlValue $data 'Tool'
    if ($v) { $Global:ZapretState.Tool = [string]$v }
    $v = Get-YamlValue $data 'WarmupSec'
    if ($null -ne $v) { $Global:ZapretState.WarmupSec = ConvertTo-Int $v 2 }
    $v = Get-YamlValue $data 'TimeoutSec'
    if ($null -ne $v) { $Global:ZapretState.TimeoutSec = ConvertTo-Int $v 4 }
    $v = Get-YamlValue $data 'MaxDomains'
    if ($null -ne $v) { $Global:ZapretState.MaxDomains = ConvertTo-Int $v 0 }
    $v = Get-YamlValue $data 'MinScore'
    if ($null -ne $v) { $Global:ZapretState.MinScore = ConvertTo-Int $v 1 }
    $v = Get-YamlValue $data 'MinScorePercent'
    if ($null -ne $v) { $Global:ZapretState.MinScorePercent = ConvertTo-Int $v 50 }
    $v = Get-YamlValue $data 'TopN'
    if ($null -ne $v) { $Global:ZapretState.TopN = ConvertTo-Int $v 20 }
    $v = Get-YamlValue $data 'TargetScore'
    if ($null -ne $v) { $Global:ZapretState.TargetScore = ConvertTo-Int $v 35 }
    $v = Get-YamlValue $data 'PreTestCount'
    if ($null -ne $v) { $Global:ZapretState.PreTestCount = ConvertTo-Int $v 12 }
    $v = Get-YamlValue $data 'PreTestPassScore'
    if ($null -ne $v) { $Global:ZapretState.PreTestPassScore = ConvertTo-Int $v 8 }
    $v = Get-YamlValue $data 'PreTestUrls'
    if ($null -ne $v) { $Global:ZapretState.PreTestUrls = [string]$v }
    $v = Get-YamlValue $data 'PreTestAllDomains'
    if ($null -ne $v) { $Global:ZapretState.PreTestAllDomains = ConvertTo-Bool $v $false }
    $v = Get-YamlValue $data 'RandomCount'
    if ($null -ne $v) { $Global:ZapretState.RandomCount = ConvertTo-Int $v 0 }
    $v = Get-YamlValue $data 'BaselineCheckCount'
    if ($null -ne $v) { $Global:ZapretState.BaselineCheckCount = ConvertTo-Int $v 40 }
    $v = Get-YamlValue $data 'AutoStopOnPerfect'
    if ($null -ne $v) { $Global:ZapretState.AutoStopOnPerfect = ConvertTo-Bool $v $true }
    $v = Get-YamlValue $data 'KeepAllWorking'
    if ($null -ne $v) { $Global:ZapretState.KeepAllWorking = ConvertTo-Bool $v $true }
    $v = Get-YamlValue $data 'TestDepth'
    if ($null -ne $v) { $Global:ZapretState.TestDepth = ConvertTo-Int $v 2 }
    $v = Get-YamlValue $data 'BinDepth'
    if ($null -ne $v) { $Global:ZapretState.BinDepth = ConvertTo-Int $v 1 }
    $v = Get-YamlValue $data 'ResultFile'
    if ($v) { $Global:ZapretState.ResultFile = [string]$v }
    $v = Get-YamlValue $data 'ProgressFile'
    if ($v) { $Global:ZapretState.ProgressFile = [string]$v }
    $v = Get-YamlValue $data 'Hostlist'
    if ($v) { $Global:ZapretState.Hostlist = [string]$v }
    $v = Get-YamlValue $data 'HostlistExclude'
    if ($v) { $Global:ZapretState.HostlistExclude = [string]$v }

    # ─── Методы / split-pos / fooling / autottl ───
    $Global:ZapretState.Methods        = @()
    $Global:ZapretState.SplitPositions = @()
    $Global:ZapretState.Foolings       = @()
    $Global:ZapretState.Autottls       = @()

    foreach ($k in $data.Keys) {
        $val = [string]$data[$k]

        if ($k -match '^Method_(.+)$') {
            if (-not [string]::IsNullOrWhiteSpace($val)) { $Global:ZapretState.Methods += $val }
        }
        elseif ($k -match '^SplitPos_(.+)$') {
            if (-not [string]::IsNullOrWhiteSpace($val)) { $Global:ZapretState.SplitPositions += $val }
        }
        elseif ($k -match '^Fooling_(.+)$') {
            if (-not [string]::IsNullOrWhiteSpace($val)) { $Global:ZapretState.Foolings += $val }
        }
        elseif ($k -match '^Autottl_(.+)$') {
            $Global:ZapretState.Autottls += $val
        }
    }

    # ─── Именованные Fake* ───
    foreach ($pair in @(
        @('FakeTLS_Google',  'FakeTLS_Google'),
        @('FakeTLS_Google2', 'FakeTLS_Google2'),
        @('FakeTLS_MaxRu',   'FakeTLS_MaxRu'),
        @('FakeTLS_4PDA',    'FakeTLS_4PDA'),
        @('FakeTLS_Sferum',  'FakeTLS_Sferum'),
        @('FakeTLS_5ka',     'FakeTLS_5ka'),
        @('FakeQUIC_Google', 'FakeQUIC_Google'),
        @('FakeQUIC_Discord','FakeQUIC_Discord'),
        @('FakeQUIC_4PDA',   'FakeQUIC_4PDA'),
        @('FakeQUIC_Rutube', 'FakeQUIC_Rutube'),
        @('FakeQUIC_Steam',  'FakeQUIC_Steam'),
        @('FakeQUIC_Tencent','FakeQUIC_Tencent'),
        @('FakeQUIC_5ka',    'FakeQUIC_5ka'),
        @('FakeUDP_STUN',    'FakeUDP_STUN'),
        @('FakeUDP_STUN2',   'FakeUDP_STUN2'),
        @('FakeUDP_Game',    'FakeUDP_Game'),
        @('FakeUDP_Discord', 'FakeUDP_Discord')
    )) {
        $v = Get-YamlValue $data $pair[0]
        if ($v) { $Global:ZapretState[$pair[1]] = [string]$v }
    }

    # ─── Пулы Fake* ───
    $Global:ZapretState.FakeTLSPool  = @()
    $Global:ZapretState.FakeQUICPool = @()
    $Global:ZapretState.FakeUDPPool  = @()

    foreach ($k in $data.Keys) {
        $val = [string]$data[$k]
        if (-not $val) { continue }

        if ($k -match '^FakeTLS_')      { $Global:ZapretState.FakeTLSPool  += $val }
        elseif ($k -match '^FakeQUIC_') { $Global:ZapretState.FakeQUICPool += $val }
        elseif ($k -match '^FakeUDP_')  { $Global:ZapretState.FakeUDPPool  += $val }
    }

    # ─── Прочее ───
    $v = Get-YamlValue $data 'ForceBin'
    if ($null -ne $v) { $Global:ZapretState.ForceBin = ConvertTo-Bool $v $false }
    $v = Get-YamlValue $data 'UseFakeTLS'
    if ($null -ne $v) { $Global:ZapretState.UseFakeTLS = ConvertTo-Bool $v $true }
    $v = Get-YamlValue $data 'UseFakeQUIC'
    if ($null -ne $v) { $Global:ZapretState.UseFakeQUIC = ConvertTo-Bool $v $false }
    $v = Get-YamlValue $data 'UseFakeHTTP'
    if ($null -ne $v) { $Global:ZapretState.UseFakeHTTP = ConvertTo-Bool $v $false }

    # ─── DNS UDP ───
    $Global:ZapretState.DnsServers    = @()
    $Global:ZapretState.DnsServerKeys = @()
    foreach ($k in $data.Keys) {
        if ($k -eq 'DnsTestDomain') { continue }
        if ($k -match '^Dns_([A-Za-z0-9_]+)$') {
            $val = [string]$data[$k]
            if ($val -match '^\d{1,3}(\.\d{1,3}){3}$') {
                $Global:ZapretState.DnsServers    += $val
                $Global:ZapretState.DnsServerKeys += $k
            }
        }
    }
    $v = Get-YamlValue $data 'DnsTestDomain'
    if ($v) { $Global:ZapretState.DnsTestDomain = [string]$v }

    # ─── DoH ───
    $Global:ZapretState.DohServers    = @()
    $Global:ZapretState.DohServerKeys = @()
    foreach ($k in $data.Keys) {
        if ($k -eq 'DohTestDomain') { continue }
        if ($k -match '^Doh_([A-Za-z0-9_]+)$') {
            $val = [string]$data[$k]
            if ($val -match '^https://') {
                $Global:ZapretState.DohServers    += $val
                $Global:ZapretState.DohServerKeys += $k
            }
        }
    }
    $v = Get-YamlValue $data 'DohTestDomain'
    if ($v) { $Global:ZapretState.DohTestDomain = [string]$v }

    # ─── Дефолты ───
    if ($Global:ZapretState.Methods.Count -eq 0) {
        $Global:ZapretState.Methods = @("split2","disorder2","multisplit","multidisorder","fakedsplit")
    }
    if ($Global:ZapretState.SplitPositions.Count -eq 0) {
        $Global:ZapretState.SplitPositions = @("1","2","midsld")
    }
    if ($Global:ZapretState.Foolings.Count -eq 0) {
        $Global:ZapretState.Foolings = @("","md5sig","badseq")
    }
    if ($Global:ZapretState.Autottls.Count -eq 0) {
        $Global:ZapretState.Autottls = @("","2","4")
    }

    # ─── Отчёт ───
    Write-Host ("  Methods={0} SplitPos={1} Foolings={2} Autottls={3}" -f `
        $Global:ZapretState.Methods.Count, $Global:ZapretState.SplitPositions.Count, `
        $Global:ZapretState.Foolings.Count, $Global:ZapretState.Autottls.Count) -ForegroundColor Gray
    Write-Host ("  Pools: TLS={0} QUIC={1} UDP={2}" -f `
        $Global:ZapretState.FakeTLSPool.Count, `
        $Global:ZapretState.FakeQUICPool.Count, `
        $Global:ZapretState.FakeUDPPool.Count) -ForegroundColor Gray

    Write-Host "  [i] Движок: zapret1 (winws.exe)" -ForegroundColor Gray
    Write-Host ("  BIN: ForceBin={0} FakeTLS={1} FakeQUIC={2} FakeHTTP={3}" -f `
        $Global:ZapretState.ForceBin, $Global:ZapretState.UseFakeTLS, `
        $Global:ZapretState.UseFakeQUIC, $Global:ZapretState.UseFakeHTTP) -ForegroundColor Gray
    Write-Host ("  DNS={0}  DoH={1}  PreTestAllDomains={2}" -f `
        $Global:ZapretState.DnsServers.Count, $Global:ZapretState.DohServers.Count, `
        $Global:ZapretState.PreTestAllDomains) -ForegroundColor Gray
    Write-Host "  ────────────────────────────────────────────" -ForegroundColor DarkCyan
    Write-Host ""
}

# === SAVE-SETTINGS ===
function Save-Settings {
    $file = $Global:ZapretState.ConfigFile
    $dir  = Split-Path $file -Parent
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }

    # ─── Preserved: строки, которые не входят в $hash ───
    $preserved = @()
    if (Test-Path $file) {
        $raw = [System.IO.File]::ReadAllText($file, [System.Text.Encoding]::UTF8)
        foreach ($line in ($raw -split "`r?`n")) {
            if ($line -match '^\s*#?\s*(Method_|SplitPos_|Fooling_|Autottl_|Repeats_|Cutoff_|FakeTLS_|FakeQUIC_|FakeUDP_|SplitSeqovl|Hostfakesplit_|FakedsplitPattern_|WfTcp|WfUdp|FilterL7|WfIface|WfL3|UseIpsetExclude|UseHostlistExclude|Debug)') {
                $preserved += $line
            }
        }
    }

    $hash = [ordered]@{
        WinwsPath          = [string]$Global:ZapretState.WinwsPath
        TxtPath            = [string]$Global:ZapretState.TxtPath
        BinPath            = [string]$Global:ZapretState.BinPath
        Tool               = [string]$Global:ZapretState.Tool
        WarmupSec          = [string]$Global:ZapretState.WarmupSec
        TimeoutSec         = [string]$Global:ZapretState.TimeoutSec
        MaxDomains         = [string]$Global:ZapretState.MaxDomains
        MinScore           = [string]$Global:ZapretState.MinScore
        MinScorePercent    = [string]$Global:ZapretState.MinScorePercent
        TopN               = [string]$Global:ZapretState.TopN
        TargetScore        = [string]$Global:ZapretState.TargetScore
        PreTestCount       = [string]$Global:ZapretState.PreTestCount
        PreTestPassScore   = [string]$Global:ZapretState.PreTestPassScore
        PreTestUrls        = [string]$Global:ZapretState.PreTestUrls
        PreTestAllDomains  = [string]$Global:ZapretState.PreTestAllDomains
        RandomCount        = [string]$Global:ZapretState.RandomCount
        BaselineCheckCount = [string]$Global:ZapretState.BaselineCheckCount
        AutoStopOnPerfect  = [string]$Global:ZapretState.AutoStopOnPerfect
        KeepAllWorking     = [string]$Global:ZapretState.KeepAllWorking
        TestDepth          = [string]$Global:ZapretState.TestDepth
        BinDepth           = [string]$Global:ZapretState.BinDepth
        ResultFile         = [string]$Global:ZapretState.ResultFile
        ProgressFile       = [string]$Global:ZapretState.ProgressFile
        ForceBin           = [string]$Global:ZapretState.ForceBin
        UseFakeTLS         = [string]$Global:ZapretState.UseFakeTLS
        UseFakeQUIC        = [string]$Global:ZapretState.UseFakeQUIC
        UseFakeHTTP        = [string]$Global:ZapretState.UseFakeHTTP
        Hostlist           = [string]$Global:ZapretState.Hostlist
        HostlistExclude    = [string]$Global:ZapretState.HostlistExclude
    }

    $yaml = ConvertTo-SimpleYaml $hash
    Set-Content -Path $file -Value $yaml -Encoding UTF8

    if ($preserved.Count -gt 0) {
        $yaml2 = "`r`n# === METHODS / FAKES ===`r`n"
        $yaml2 += ($preserved -join "`r`n") + "`r`n"
        Add-Content -Path $file -Value $yaml2 -Encoding UTF8
    }

    $dnsBlock  = "`r`n# === DNS SERVERS (UDP) ===`r`n"
    $dnsBlock += ("DnsTestDomain: `"$($Global:ZapretState.DnsTestDomain)`"`r`n")
    $dnsBlock += "`r`n"
    for ($j = 0; $j -lt $Global:ZapretState.DnsServers.Count; $j++) {
        $key = if ($j -lt $Global:ZapretState.DnsServerKeys.Count -and $Global:ZapretState.DnsServerKeys[$j]) {
            $Global:ZapretState.DnsServerKeys[$j]
        } else { "Dns_Server$($j + 1)" }
        $dnsBlock += ("{0}: `"{1}`"`r`n" -f $key, $Global:ZapretState.DnsServers[$j])
    }
    Add-Content -Path $file -Value $dnsBlock -Encoding UTF8

    $dohBlock  = "`r`n# === DNS-over-HTTPS (DoH) ===`r`n"
    $dohBlock += ("DohTestDomain: `"$($Global:ZapretState.DohTestDomain)`"`r`n")
    $dohBlock += "`r`n"
    for ($j = 0; $j -lt $Global:ZapretState.DohServers.Count; $j++) {
        $key = if ($j -lt $Global:ZapretState.DohServerKeys.Count -and $Global:ZapretState.DohServerKeys[$j]) {
            $Global:ZapretState.DohServerKeys[$j]
        } else { "Doh_Server$($j + 1)" }
        $dohBlock += ("{0}: `"{1}`"`r`n" -f $key, $Global:ZapretState.DohServers[$j])
    }
    Add-Content -Path $file -Value $dohBlock -Encoding UTF8

    Write-Log "settings.yml saved"
}

# === WRITE-LOG ===
function Write-Log($msg, $level = "INFO") {
    $time = Get-Date -Format "HH:mm:ss"
    $color = switch ($level) {
        "ERR"  { "Red" }
        "WARN" { "Yellow" }
        default { "Green" }
    }
    Write-Host "[$time][$level] $msg" -ForegroundColor $color
}